# Generated by Django 4.0.2 on 2022-02-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'MEN'), ('W', 'WOMEN')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('year', models.DateField(auto_now_add=True)),
                ('imdb', models.IntegerField()),
                ('genre', models.CharField(choices=[('M', 'Melodramma'), ('R', 'Romantic'), ('C', 'Comedy'), ('D', 'Dramma')], max_length=1)),
                ('cust', models.ManyToManyField(to='netfap.Actor')),
            ],
        ),
    ]
