# Generated by Django 4.0.2 on 2022-02-23 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netfap', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actor',
            new_name='Actors',
        ),
    ]
