# Generated by Django 4.0.2 on 2022-02-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netfap', '0002_rename_actor_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='rol',
            field=models.ManyToManyField(to='netfap.Movie'),
        ),
    ]
