# Generated by Django 4.0.2 on 2022-02-23 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netfap', '0003_actors_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actors',
            old_name='rol',
            new_name='films',
        ),
    ]
