# Generated by Django 4.0.2 on 2022-02-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netfap', '0004_rename_rol_actors_films'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('M', 'Melodramma'), ('R', 'Romantic'), ('C', 'Comedy'), ('D', 'Dramma'), ('F', 'Fantasy')], max_length=1),
        ),
    ]
