# Generated by Django 4.0.2 on 2022-02-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netfap', '0005_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='films',
            field=models.ManyToManyField(blank=True, to='netfap.Movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cust',
            field=models.ManyToManyField(blank=True, to='netfap.Actors'),
        ),
    ]
