# Generated by Django 4.0.2 on 2022-02-23 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netfap', '0006_alter_actors_films_alter_movie_cust'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actors',
            new_name='Actor',
        ),
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Aktyorlar'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Filmlar'},
        ),
    ]
